### ISSUE TITLE
Remove NTPClient used in SAMD examples

### ISSUE THREAD

**Issue by sandeepmistry** [arduino-libraries/AzureIoT#6]

**Comment by obsoleted** [comment]
I am still a bit torn on this. I understand wanting to make the samples/sketches as concise as possible. However, this type of functionality does seem out of scope for the the library itself. 
I wonder if there is another NTP library that exists (or maybe one can be made) that we could use in the samples that would limit the code there but just add another dependency. 

While NTP and Wifi are requirements for using the library successfully it feels odd to move the configuration of them into the library. Should these libraries want to expose new initial configuration options then this library would also need to be updated instead of just benefiting from new functionality.

**Comment by sandeepmistry** [comment]
@obsoleted good points, I'll submit a patch to this repo to also support non-ESP8266 boards: https://github.com/FWeinb/NTPClient

Then we can use it in the examples like you suggested.

I'll rename this issue accordingly.

**Comment by sandeepmistry** [comment]
I've submitted the following PR to the NTPClient repo: https://github.com/FWeinb/NTPClient/pull/8

**Comment by sandeepmistry** [comment]
Closed via #16.
